application:
  period: 1h
  key: /Users/artem/.ssh/id_rsa
  projects:
    yandexads:
      enable: true
      from: git@gitflic.ru:getapp/getapp-yandexads-flutter.git
      to: git@github.com:getapp-store/getapp-yandexads-flutter.git

    getapp:
      enable: false
      from: origin
      to: github
